name: Node.js CI/CD

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.3
        with: &setup-pnpm
          cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with: &setup-node
          node-version-file: .node-version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: OxLint
        run: pnpm lint:oxlint
      - name: ESLint
        run: pnpm lint:eslint
      - name: Oxfmt
        run: pnpm lint:oxfmt
      - name: Type Check
        continue-on-error: true
        run: pnpm lint:tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.3
        with: *setup-pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with: *setup-node

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Upload Page Artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: .output/public
          include-hidden-files: true

  deploy:
    name: Deploy
    needs: [build]
    concurrency:
      group: pages
      cancel-in-progress: true
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-slim
    timeout-minutes: 30
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
